### PR TITLE
Fix deprecation warnings.

### LINKED ISSUE #80: RoomSchemaLocationWorkaround added new deprecations
With some of the changes in 1.0.2, we added some unnecessary deprecations:

image

And

image

Neither of these are necessary and should be removed.

### PR DESCRIPTION
**Pull request by runningcode**
This sets the `mergeRoomSchemaLocations` as an input annotated property.

This also set the duplicate copy strategy to include duplicates.

Fixes #80

### CODE REVIEW

File: src/main/groovy/org/gradle/android/workarounds/RoomSchemaLocationWorkaround.groovy [hunk 1]
```diff
@@ -199,6 +201,7 @@ class RoomSchemaLocationWorkaround implements Workaround {
      * of those tasks if only a single variant is being assembled.
      */
     static class RoomSchemaLocationMergeTask extends DefaultTask {
+        @Input
```
Comment (ghale) [inline src/main/groovy/org/gradle/android/workarounds/RoomSchemaLocationWorkaround.groovy:204]: I think this should be `@Internal`.  I explicitly did not want this task to be incremental (and I'm not sure `@Input` would work in an expected way here, either).
